config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'
  resources :deities,     only: [:index, :show]
  resources :mythologies, only: [:index, :show]
  resources :events,      only: [:index, :show]
  resources :domains,     only: [:index, :show]
  resources :users,       only: [:new, :create, :destroy]
  
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', :to => 'sessions#create'
  delete '/logout', :to => 'sessions#destroy'
  
  get 'api/dashboard', to: 'api#dashboard'
  namespace :api do
    namespace :v1 do
      resources :deities, only: [:index, :show] do
        get 'mythology', to: 'deities/mythologies#index'
        get 'events', to: 'deities/events#index'
        get 'parents', to: 'deities/parents#index'
        get 'children', to: 'deities/children#index'
        get 'domains', to: 'deities/domains#index'
      end
      resources :mythologies, only: [:index, :show] do
        get 'deities', to: 'mythologies/deities#index'
      end
      resources :events, only: [:index, :show] do
        get 'deities', to: 'events/deities#index'
      end
      # post '/domains', to: 'domains#create'
      resources :domains, only: [:index, :show] do
        get 'deities', to: 'domains/deities#index'
      # delete '/domains', to: 'domains#destroy'
      end
      
    end
  end
  
  get "mythologies/:name/deities"          => "mythologies/deities#index"
end

app/models/deity.rb
class Deity < ApplicationRecord
  validates :tier, :gender, :mythology_id, :classification, presence: true
  validates :name, :description, presence: true, uniqueness: :true
  
  has_many :child_births, foreign_key: :parent_id, class_name: "Birth" 
  has_many :children, through: :child_births, source: :child
  has_many :parent_births, foreign_key: :child_id, class_name: "Birth"    
  has_many :parents, through: :parent_births, source: :parent
  has_many :event_actors
  has_many :events, through: :event_actors
  has_many :deity_domains
  has_many :domains, through: :deity_domains
  
  belongs_to :mythology
  
  
  # has_many :deities, through: :deity_children
  
  enum gender:    [:male, :female, :unknown, :hermaphriditic]
  enum tier:      ["Founder", "Greater God", "God", "Lesser God", "Demi-god"]
  
  def find_books_with_subject(number = 5)
    BookSearch.find_books_with_subject({title: self.name, number: number})
  end
  
  def siblings
    parent_one_siblings = Birth.where(parent: parents.first).map do |birth|
      unless birth.child == self 
        birth.child
      end
    end.compact!
    if parents.second
      parent_two_siblings = Birth.where(parent: parents.second).map do |birth|
        unless birth.child == self 
          birth.child
        end
      end.compact!
      full_siblings = parent_one_siblings.select do |sibling|
        parent_two_siblings.include?(sibling)
      end
    else
      full_siblings = parent_one_siblings
    end
    full_siblings
  end
  
end

app/controllers/api/v1/deities/children_controller.rb
module Api
  module V1
    module Deities
      class ChildrenController < ActionController::API
        def index
          @deity = Deity.find(params[:deity_id])
          @children = @deity.children
          render json: @children
        end
      end
    end
  end
end

app/controllers/api/v1/deities/domains_controller.rb
module Api
  module V1
    module Deities
      class DomainsController < ActionController::API
        def index
          @deity = Deity.find(params[:deity_id])
          @domains = @deity.domains
          render json: @domains
        end
      end
    end
  end
end

app/controllers/api/v1/deities/events_controller.rb
module Api
  module V1
    module Deities
      class EventsController < ActionController::API
        def index
          @deity = Deity.find(params[:deity_id])
          @events = @deity.events
          render json: @events
        end
      end
    end
  end
end

app/controllers/api/v1/deities/mythologies_controller.rb
module Api
  module V1
    module Deities
      class MythologiesController < ActionController::API
        def index
          @deity = Deity.find(params[:deity_id])
          @mythology = @deity.mythology
          render json: @mythology
        end
      end
    end
  end
end

app/controllers/api/v1/deities/parents_controller.rb
module Api
  module V1
    module Deities
      class ParentsController < ActionController::API
        def index
          @deity = Deity.find(params[:deity_id])
          @parents = @deity.parents
          render json: @parents
        end
      end
    end
  end
end

app/controllers/api/v1/deities_controller.rb
module Api
  module V1
    class DeitiesController < ActionController::API
      def index
        render json: Deity.all
      end
      
      def show
        @deity = Deity.find(params[:id])
        render json: @deity
      end
    end
  end
end

app/controllers/api/v1/domains/deities_controller.rb
module Api
  module V1
    module Domains
      class DeitiesController < ActionController::API
        def index
          @domain = Domain.find(params[:domain_id])
          @deities = @domain.deities
          render json: @deities
        end
      end
    end
  end
end

app/controllers/api/v1/events/deities_controller.rb
module Api
  module V1
    module Events
      class DeitiesController < ActionController::API
        def index
          @event = Event.find(params[:event_id])
          @deities = @event.deities
          render json: @deities
        end
      end
    end
  end
end

app/controllers/api/v1/mythologies/deities_controller.rb
module Api
  module V1
    module Mythologies
      class DeitiesController < ActionController::API
        def index
          @mythology = Mythology.find(params[:mythology_id])
          @deities = @mythology.deities
          render json: @deities
        end
      end
    end
  end
end

app/controllers/deities_controller.rb
class DeitiesController < ApplicationController
  def index
    unless params["mythology"] 
      @deities = Deity.all
    else
      @deities = Deity.where(mythology: Mythology.find_by(name: params["mythology"]))
    end
  end
  
  def show
    @deity = Deity.find(params[:id])
  end
end

app/controllers/mythologies/deities_controller.rb
module Mythologies
  class DeitiesController < ApplicationController
    def index
      @mythology = Mythology.find_by(name: params["name"].capitalize)
      @deities = @mythology.deities
    end
  end
end

app/views/deities/index.html.erb
<head>
  <link href='https://fonts.googleapis.com/css?family=Merienda' rel='stylesheet'>
</head>
<div class='container'>
  <div class='row'>
    <% @deities.each do |deity| %>
      <div class='center-block'>
          <div class="card border-white text-center" style="width: 17rem;">
            <div class = "card-body card-grey">  
              <ui><h5><%= link_to deity.name, deity_path(deity) %></h5></ui>
              <div>
                <ui><%= image_tag deity.image, height: 200 %></ui>
              </div>
              <ui class='my-small'><p><%= deity.description %></p></ui>
              <ui><%= link_to deity.mythology.name, mythology_path(deity.mythology) %></ui> <br />
              <ui><%= deity.classification %></ui> <br />
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/deities/show.html.erb
<head>
	<meta charset="utf-8">
	<title><%= @deity.name %></title>
</head>
<body>
	<div class = "container text-center">
		<div class="row text-center margin-top">
			<div class='col-6'>
				<%= image_tag @deity.image, height: 400  %>
        <div class='card bg-success top-margin-expand'>
          <p> Related Reading <%= "#{@deity.name}" %>  --></p>
        </div>
			</div>
			<div class='col-6 card bg-info'>
				<div class='card-body '>
  				<h2><strong><%= @deity.name %></strong></h2>
  				<p><%= @deity.description %></p>
  				<p>Gender: <%= @deity.gender %> </p>
  				<p>Power-level: <%= @deity.tier %> </p>
          <p>Domains: <% @deity.domains.each do |domain| %> 
            <br />
            <%= link_to domain.name, domain_path(domain)  %>
          <% end %>
          </p>
          <% @deity.parents.each do |parent| %>
            <% if parent.male? %>
            <p>Father: <%= link_to parent.name, deity_path(parent) %></p>
            <% elsif parent.female? %>
            <p>Mother: <%= link_to parent.name, deity_path(parent) %></p>
            <% else %>
            <p>Creator: <%= link_to parent.name, deity_path(parent) %></p>
            <% end %>
          <% end %>
          <% unless @deity.children.empty? %>
          <p class='deity-show-titles'>Children:</p>
              <% @deity.children.each do |child| %>
                <span class='spread-out'> <%= link_to child.name, deity_path(child) %></span>
              <% end %> 
          <% end %>
          <% if @deity.siblings %>
            <% if @deity.siblings.any? {|sibling| sibling.male? } %>
              <p class='deity-show-titles'>Brothers:</p>
              <% @deity.siblings.each do |sibling| %>
                <% if sibling.male? %>
                  <span class='spread-out'><%= link_to sibling.name, deity_path(sibling) %></span>
                <% end %>
              <% end %>
            <% end %>
            <% if @deity.siblings.any? {|sibling| sibling.female? } %>
              <p class='deity-show-titles'>Sisters:</p>
              <% @deity.siblings.each do |sibling| %>
                <% if sibling.female? %>
                  <span class='spread-out'><%= link_to sibling.name, deity_path(sibling) %></span>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
				</div>
			</div>
      <div class='row width-fill-page'>
		    <div class='card-body'>
          <table class ="table">
            <thead>
              <tr>
                <th></th>
                <th>Book</th>
                <th>Authors</th>
                <th>Publisher</th>
              </tr>
            </thead>
            <tbody>
              <% unless @deity.find_books_with_subject.nil? %>
                <% @deity.find_books_with_subject.each do |book| %>
                  <% if book.image %>
                    <td class='book-image'><%= image_tag book.image %></td>
                  <% else %>
                    <td></td>
                  <% end %>
                  <td class='book-title'><%= link_to book.title, book.store_link %></td>
                  <% if book.authors %>
                    <td class='book-author'><% book.authors.each do |author| %>
                       <%= author %> <br />
                     <% end %> </td>
                  <% else %>
                      <td></td>
                  <% end %>
                  <% if book.publisher %>
                  <td class='book-publisher'><%= book.publisher %></td>
                  <% else %>
                    <td></td>
                  <% end %>
                  </tr>
                <% end %>
              <% else %>
                  <td>This Mythology has no Books associated with its name</td>
              <% end %>
            </tbody>
          </table>
        </div>
			</div>
		</div>
	</div>

</body>