config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'
  resources :deities,     only: [:index, :show]
  resources :mythologies, only: [:index, :show]
  resources :events,      only: [:index, :show]
  resources :domains,     only: [:index, :show]
  resources :users,       only: [:new, :create, :destroy]
  
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', :to => 'sessions#create'
  delete '/logout', :to => 'sessions#destroy'
  
  get 'api/dashboard', to: 'api#dashboard'
  namespace :api do
    namespace :v1 do
      resources :deities, only: [:index, :show] do
        get 'mythology', to: 'deities/mythologies#index'
        get 'events', to: 'deities/events#index'
        get 'parents', to: 'deities/parents#index'
        get 'children', to: 'deities/children#index'
        get 'domains', to: 'deities/domains#index'
      end
      resources :mythologies, only: [:index, :show] do
        get 'deities', to: 'mythologies/deities#index'
      end
      resources :events, only: [:index, :show] do
        get 'deities', to: 'events/deities#index'
      end
      # post '/domains', to: 'domains#create'
      resources :domains, only: [:index, :show] do
        get 'deities', to: 'domains/deities#index'
      # delete '/domains', to: 'domains#destroy'
      end
      
    end
  end
  
  get "mythologies/:name/deities"          => "mythologies/deities#index"
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :event_actors
  has_many :deities, through: :event_actors
  
  validates :title, :description, presence: true, uniqueness: true
end

app/controllers/api/v1/deities/events_controller.rb
module Api
  module V1
    module Deities
      class EventsController < ActionController::API
        def index
          @deity = Deity.find(params[:deity_id])
          @events = @deity.events
          render json: @events
        end
      end
    end
  end
end

app/controllers/api/v1/events/deities_controller.rb
module Api
  module V1
    module Events
      class DeitiesController < ActionController::API
        def index
          @event = Event.find(params[:event_id])
          @deities = @event.deities
          render json: @deities
        end
      end
    end
  end
end

app/controllers/api/v1/events_controller.rb
module Api
  module V1
    class EventsController < ActionController::API
      def index
        @events = Event.all
        render json: @events
      end
      
      def show
        @event = Event.find(params[:id])
        render json: @event
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end
  
  def show
    @event = Event.find(params[:id])
    @mythology = Mythology.find(@event.mythology_id)
  end
end

app/views/events/index.html.erb
<div class='container'>
  <h2> Myths: </h2>
  <div class='row'>
    <% @events.each do |event| %>
      <div class='center-block'>
          <div class="card border-white text-center" style="width: 17rem;">
            <div class = "card-body">  
              <ui><h5><%= link_to event.title, event_path(event) %></h5></ui>
              <ui class='my-small'>(<%= Mythology.find(event.mythology_id).name %>)</ui> <br />
              <li class='my-small'><%= event.description %></li> <br />
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class='container'>
  <h2>  <%=  @event.title %> </h2>
  <h3 class='my-small'> (<%= @mythology.name %>) </h3>
  <h3 class='my-small'> <%= @event.description %> </h3>
  <div class ='row'>
    <% @event.deities.each do |deity| %>
      <div class='center-block'>
          <div class="card border-white text-center" style="width: 17rem;">
            <div class = "card-body">  
              <ui><h5><%= link_to deity.name, deity_path(deity) %></h5></ui>
              <div>
                <ui><%= image_tag deity.image, height: 200 %></ui>
              </div>
              <li class='my-small'><%= deity.description %></li> <br />
              <ui><%= link_to deity.mythology.name, mythology_path(deity.mythology) %></ui> <br />
              <ui><%= deity.classification %></ui> <br />
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>